var = 0x1A
print(r'value of var is {var}')
print(r'value of var is {hex(var)}')
print(r'value of var is {oct(var)}')
print(r'value of var is {bin(var)}')
print('-------------------------------------')
print(f'value of var is {var}')
print(f'value of var is {hex(var)}')
print(f'value of var is {oct(var)}')
print(f'value of var is {bin(var)}')
print('-------------------------------------')
print(b'value of var is {var}')